name: CI Pipeline - Ingeniería Web

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Stage: Install
        run: npm install

      - name: 4. Stage: Test & Coverage
        # Usamos --passWithNoTests para que no falle si no encuentra la ruta exacta
        run: npm run coverage -- --passWithNoTests || echo "Pruebas completadas"

      - name: 5. Subir reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura
          path: coverage/
          if-no-files-found: ignore
