name: CI Pipeline Ingenieria Web

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Stage Install
        run: npm install

      - name: Stage Test y Coverage
        run: npx test -- --coverage --passWithNoTests

      - name: Subir reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura
          path: coverage/
